# system "defaults write -g ApplePressAndHoldEnabled -bool false"
# system "defaults write -g InitialKeyRepeat -int 10"
# system "defaults write -g KeyRepeat -int 1"
# system "defaults write com.apple.dock persistent-apps -array"
tap "disrupted/neovim-nightly"
tap "koekeishiya/formulae"
tap "oven-sh/bun"
brew "alejandra"
brew "direnv"
brew "node"
brew "docker-compose-langserver"
brew "dockerfile-language-server"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "go", postinstall: "/opt/homebrew/bin/go telemetry off"
brew "gofumpt"
brew "openjdk", postinstall: "mkdir -p ~/Library/Java/JavaVirtualMachines && ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk ~/Library/Java/JavaVirtualMachines/openjdk.jdk"
brew "google-java-format"
brew "gopls"
brew "imagemagick"
brew "python@3.14"
brew "jdtls"
brew "lazydocker"
brew "lazygit"
brew "lua-language-server"
brew "mpv", postinstall: "bash -lc 'curl -L https://raw.githubusercontent.com/9beach/mpv-app-bundle/main/install-raw.sh | bash'"
brew "duti", postinstall: "for ext in mkv mp4 webm m3u; do /opt/homebrew/bin/duti -s org.mpv-player.macos '$ext' all; done"
brew "prettier"
brew "pyright"
brew "python@3.12"
brew "python@3.13"
brew "ripgrep"
brew "ruff"
brew "rust"
brew "rust-analyzer"
brew "stow"
brew "stylua"
brew "superhtml"
brew "swift-format"
brew "tree"
brew "tree-sitter-cli"
brew "typescript"
brew "typescript-language-server"
brew "uv"
brew "vscode-langservers-extracted"
brew "yaml-language-server"
brew "yamlfmt"
brew "zig"
brew "zls"
brew "zoxide"
brew "koekeishiya/formulae/skhd", postinstall: "/opt/homebrew/bin/skhd --install-service && /opt/homebrew/bin/skhd --start-service"
brew "oven-sh/bun/bun"
cask "font-iosevka-nerd-font", greedy: true
cask "font-iosevka-ss03", greedy: true
cask "helium-browser", greedy: true
cask "kitty", greedy: true
cask "neovim-nightly", greedy: true
cask "orbstack", greedy: true
# system "/Applications/OrbStack.app/Contents/MacOS/bin/orbctl config set app.start_at_login true"
# system "/Applications/OrbStack.app/Contents/MacOS/bin/orbctl config set rosetta false"
# system "/Applications/OrbStack.app/Contents/MacOS/bin/orbctl config set setup.use_admin false"
# system "open 'x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles'"
