theme = "tokyonight_transparent"

[editor]
line-number = "relative"
file-picker.hidden = false
cursor-shape.insert = "bar"
auto-info = false
cursorline = true

[editor.statusline]
left = []
center = []
right = []
separator = "│"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
Z = { Z = ":x", Q = ":q!"}
space = { c = [":open ~/src/nix"] }

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
