[[language]]
name = "lua"
language-servers = [ "lua-language-server" ]
formatter = { command = "stylua", args = ["--indent-type", "Spaces","--indent-width", "2", "--column-width", "100" ,"-"] }
auto-format = true

[[language]]
name = "c"
formatter = { command = "clang-format", args = ["--style=Google"] }
auto-format = true

[[language]]
name = "cpp"
formatter = { command = "clang-format", args = ["--style=Google"] }
auto-format = true

[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
formatter = { command = "ruff", args = ["format", "-"] }
auto-format = true

[[language]]
name = "java"
formatter = { command = 'google-java-format', args = ['-'] }
auto-format = true

[[language]]
name = "go"
formatter = { command = "gofumpt" }
auto-format = true

[[language]]
name = "rust"
formatter = { command = "rustfmt" }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "yaml"
language-servers = [ "yaml-language-server" ]
formatter = { command = "yamlfmt", args = ["-"] }
auto-format = true
